# Generated by Django 4.2.5 on 2024-05-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(default='', max_length=100)),
                ('fa_name', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('sid', models.TextField(default='', max_length=50)),
                ('link', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('short_cut', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('full_title', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('short_title', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('link', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('home', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('vname', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('html', models.TextField(blank=True, default='<div class="col-md-5">\n                <div class="card">\n                    <div class="card-header">\n                        <h5 class="title">\n                            Important updates posted sooner than you expect – stay connected!\n                        </h5>\n                    </div>\n                    <div class="card-body">\n                        <div class="toolbar">\n                            <h6>\n                                Any Suggestions or Complaints?  \n                                <a href="/contact/" class="text-info text-capitalize">Contact Us</a>\n                            </h6>\n                        </div>\n                    </div>\n                </div>\n            </div>', max_length=30000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='category.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('link', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('link_text', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('html', models.TextField(blank=True, default='', max_length=30000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('sub', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='category.subcategorymodel')),
            ],
        ),
    ]
