# Generated by Django 4.2.5 on 2024-05-17 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.TextField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConfessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=1000)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('likes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('comments', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('msg', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopedByModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('short_name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('linkedin', models.TextField(max_length=100)),
                ('instagram', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='developer/')),
                ('image_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopedGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('style', models.CharField(default='', max_length=1000)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('image_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('faculty_type', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MscNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msc_name', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PdfDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='RedirectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=500)),
                ('send_message', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('redirect_to', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('html_page', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('html_code', models.TextField(blank=True, default='', max_length=500000, null=True)),
                ('change_redirect', models.BooleanField(blank=True, default=False, null=True)),
                ('template_name', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SendMailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_start', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.BigIntegerField()),
                ('name', models.TextField(max_length=50)),
                ('branch', models.TextField(max_length=50)),
                ('contact', models.BigIntegerField(default=0)),
                ('division', models.TextField(max_length=100)),
                ('roll_no', models.BigIntegerField(default=0)),
                ('total_mark', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='', max_length=100)),
                ('subject_full_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YearBatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_A', models.BigIntegerField(default=0)),
                ('section_B', models.BigIntegerField(default=0)),
                ('msc', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.mscnamemodel')),
                ('sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.semmodel')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.studentdatamodel')),
                ('subject', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.subjectnamemodel')),
            ],
        ),
        migrations.AddField(
            model_name='studentdatamodel',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.yearbatchmodel'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(default='aiml', max_length=100, null=True)),
                ('user_type', models.CharField(default='student', max_length=100, null=True)),
                ('image_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('auth_token', models.CharField(max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('is_delete', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfessionLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('confession', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confession_like', to='User.confessionmodel')),
                ('student', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_confession_like', to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ConfessionCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('confession', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confession_comment', to='User.confessionmodel')),
                ('student', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_confession_comment', to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ActualRollNoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.BigIntegerField(default=0)),
                ('division', models.CharField(default='', max_length=100)),
                ('sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.semmodel')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.studentdatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='AccessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(default='no', max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
    ]
